#!/bin/sh
# Docker entrypoint script to inject environment variables into the UI
# This allows runtime configuration of API_BASE_URL and REDIS_INSIGHT_URL

CONFIG_FILE="/usr/share/nginx/html/config.js"

# Generate config.js with environment variables
cat > $CONFIG_FILE << EOF
// Runtime configuration - auto-generated by docker-entrypoint.sh
window.API_BASE_URL = '${API_BASE_URL:-http://localhost:8000}';
window.REDIS_INSIGHT_URL = '${REDIS_INSIGHT_URL:-}';
EOF

echo "Generated config.js:"
cat $CONFIG_FILE

# Execute the original command
exec "$@"
